// 国家/地区数据：城市为主要城市中心坐标 [名称, 纬度, 经度, 随机半径(度)]
// fmt 地址格式: NS=门牌在前(12 Main St)  SN=门牌在后(Hauptstraße 12)  "S,N"=街道,门牌(Calle Mayor, 12)
// phones 电话模板: # = 0-9 随机数字, N = 2-9 随机数字
// m/f/l = 男名/女名/姓氏池；CJK 地区另有 mr/fr/lr 对应罗马化（用于生成邮箱）
const COUNTRIES = {
  US: {
    flag: '🇺🇸', name: '美国', en: 'United States', lang: 'en', fmt: 'NS',
    cities: [['New York', 40.73, -73.99, .06], ['Los Angeles', 34.05, -118.26, .08], ['Chicago', 41.88, -87.66, .06], ['Seattle', 47.61, -122.33, .05], ['Boston', 42.35, -71.07, .04]],
    phones: ['+1 212 N## ####', '+1 415 N## ####', '+1 312 N## ####', '+1 206 N## ####', '+1 617 N## ####'],
    m: ['James', 'Michael', 'David', 'Daniel', 'Ryan', 'Kevin', 'Tyler', 'Ethan'],
    f: ['Emily', 'Sarah', 'Jessica', 'Ashley', 'Emma', 'Olivia', 'Megan', 'Lauren'],
    l: ['Smith', 'Johnson', 'Brown', 'Miller', 'Davis', 'Wilson', 'Anderson', 'Taylor'],
  },
  CA: {
    flag: '🇨🇦', name: '加拿大', en: 'Canada', lang: 'en', fmt: 'NS',
    cities: [['Toronto', 43.66, -79.39, .06], ['Vancouver', 49.26, -123.11, .04], ['Montreal', 45.51, -73.57, .05], ['Calgary', 51.04, -114.07, .05]],
    phones: ['+1 416 N## ####', '+1 604 N## ####', '+1 514 N## ####', '+1 403 N## ####'],
    m: ['Liam', 'Noah', 'William', 'Benjamin', 'Lucas', 'Owen', 'Nathan', 'Jack'],
    f: ['Charlotte', 'Sophie', 'Chloe', 'Hannah', 'Grace', 'Ella', 'Abigail', 'Zoe'],
    l: ['Martin', 'Roy', 'Tremblay', 'Campbell', 'Stewart', 'Scott', 'MacDonald', 'White'],
  },
  UK: {
    flag: '🇬🇧', name: '英国', en: 'United Kingdom', lang: 'en', fmt: 'NS',
    cities: [['London', 51.51, -0.12, .08], ['Manchester', 53.48, -2.24, .04], ['Birmingham', 52.48, -1.90, .04], ['Edinburgh', 55.95, -3.19, .03]],
    phones: ['+44 74## ######', '+44 75## ######', '+44 77## ######', '+44 79## ######'],
    m: ['Oliver', 'George', 'Harry', 'Charlie', 'Thomas', 'Oscar', 'Alfie', 'Henry'],
    f: ['Amelia', 'Isla', 'Lily', 'Freya', 'Poppy', 'Daisy', 'Alice', 'Florence'],
    l: ['Jones', 'Williams', 'Evans', 'Thomas', 'Roberts', 'Walker', 'Wright', 'Hughes'],
  },
  DE: {
    flag: '🇩🇪', name: '德国', en: 'Germany', lang: 'de', fmt: 'SN',
    cities: [['Berlin', 52.52, 13.40, .07], ['München', 48.14, 11.57, .05], ['Hamburg', 53.55, 9.99, .05], ['Köln', 50.94, 6.95, .04], ['Frankfurt', 50.11, 8.68, .04]],
    phones: ['+49 151 ########', '+49 160 #######', '+49 170 #######', '+49 176 ########'],
    m: ['Lukas', 'Felix', 'Jonas', 'Maximilian', 'Paul', 'Leon', 'Finn', 'Moritz'],
    f: ['Anna', 'Lena', 'Marie', 'Laura', 'Julia', 'Sophie', 'Hannah', 'Clara'],
    l: ['Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Wagner', 'Becker', 'Hoffmann'],
  },
  FR: {
    flag: '🇫🇷', name: '法国', en: 'France', lang: 'fr', fmt: 'NS',
    cities: [['Paris', 48.86, 2.34, .05], ['Lyon', 45.76, 4.84, .03], ['Marseille', 43.30, 5.38, .04], ['Toulouse', 43.60, 1.44, .03]],
    phones: ['+33 6 ## ## ## ##', '+33 7 ## ## ## ##'],
    m: ['Lucas', 'Hugo', 'Louis', 'Gabriel', 'Arthur', 'Jules', 'Théo', 'Antoine'],
    f: ['Emma', 'Léa', 'Chloé', 'Manon', 'Camille', 'Louise', 'Juliette', 'Alice'],
    l: ['Martin', 'Bernard', 'Dubois', 'Petit', 'Durand', 'Leroy', 'Moreau', 'Fournier'],
  },
  IT: {
    flag: '🇮🇹', name: '意大利', en: 'Italy', lang: 'it', fmt: 'SN',
    cities: [['Roma', 41.90, 12.49, .05], ['Milano', 45.47, 9.19, .04], ['Torino', 45.07, 7.68, .03], ['Bologna', 44.49, 11.34, .03]],
    phones: ['+39 320 #######', '+39 333 #######', '+39 347 #######', '+39 389 #######'],
    m: ['Francesco', 'Alessandro', 'Lorenzo', 'Matteo', 'Andrea', 'Gabriele', 'Marco', 'Luca'],
    f: ['Sofia', 'Giulia', 'Aurora', 'Alice', 'Martina', 'Chiara', 'Francesca', 'Elena'],
    l: ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci'],
  },
  ES: {
    flag: '🇪🇸', name: '西班牙', en: 'Spain', lang: 'es', fmt: 'S,N',
    cities: [['Madrid', 40.42, -3.70, .05], ['Barcelona', 41.39, 2.16, .04], ['Valencia', 39.47, -0.38, .03], ['Sevilla', 37.39, -5.99, .03]],
    phones: ['+34 6## ### ###', '+34 7## ### ###'],
    m: ['Alejandro', 'Daniel', 'Pablo', 'Hugo', 'Álvaro', 'Adrián', 'David', 'Javier'],
    f: ['Lucía', 'María', 'Paula', 'Sofía', 'Carmen', 'Valeria', 'Sara', 'Marta'],
    l: ['García', 'Rodríguez', 'Martínez', 'López', 'Sánchez', 'Pérez', 'Gómez', 'Fernández'],
  },
  NL: {
    flag: '🇳🇱', name: '荷兰', en: 'Netherlands', lang: 'nl', fmt: 'SN',
    cities: [['Amsterdam', 52.37, 4.90, .04], ['Rotterdam', 51.92, 4.48, .04], ['Utrecht', 52.09, 5.12, .03], ['Den Haag', 52.08, 4.30, .03]],
    phones: ['+31 6 ########'],
    m: ['Daan', 'Sem', 'Lucas', 'Finn', 'Luuk', 'Thijs', 'Lars', 'Bram'],
    f: ['Emma', 'Julia', 'Sophie', 'Lotte', 'Fleur', 'Sanne', 'Anna', 'Lieke'],
    l: ['de Jong', 'Jansen', 'de Vries', 'van den Berg', 'Bakker', 'Visser', 'Smit', 'Meijer'],
  },
  CH: {
    flag: '🇨🇭', name: '瑞士', en: 'Switzerland', lang: 'de', fmt: 'SN',
    cities: [['Zürich', 47.38, 8.54, .03], ['Genève', 46.20, 6.15, .03], ['Basel', 47.56, 7.59, .03], ['Bern', 46.95, 7.44, .02]],
    phones: ['+41 76 ### ## ##', '+41 78 ### ## ##', '+41 79 ### ## ##'],
    m: ['Noah', 'Liam', 'Matteo', 'Luca', 'Leon', 'David', 'Gabriel', 'Julian'],
    f: ['Mia', 'Emma', 'Lina', 'Elena', 'Lara', 'Anna', 'Nina', 'Alina'],
    l: ['Müller', 'Meier', 'Schmid', 'Keller', 'Weber', 'Huber', 'Schneider', 'Steiner'],
  },
  AT: {
    flag: '🇦🇹', name: '奥地利', en: 'Austria', lang: 'de', fmt: 'SN',
    cities: [['Wien', 48.21, 16.37, .05], ['Graz', 47.07, 15.44, .03], ['Linz', 48.31, 14.29, .02], ['Salzburg', 47.80, 13.04, .02]],
    phones: ['+43 660 #######', '+43 664 #######', '+43 676 #######'],
    m: ['Lukas', 'David', 'Tobias', 'Felix', 'Simon', 'Jakob', 'Maximilian', 'Elias'],
    f: ['Anna', 'Lena', 'Sophia', 'Emma', 'Laura', 'Marie', 'Johanna', 'Valentina'],
    l: ['Gruber', 'Huber', 'Bauer', 'Wagner', 'Pichler', 'Steiner', 'Moser', 'Mayer'],
  },
  SE: {
    flag: '🇸🇪', name: '瑞典', en: 'Sweden', lang: 'sv', fmt: 'SN',
    cities: [['Stockholm', 59.33, 18.06, .05], ['Göteborg', 57.71, 11.97, .04], ['Malmö', 55.60, 13.00, .03]],
    phones: ['+46 70 ### ## ##', '+46 72 ### ## ##', '+46 73 ### ## ##'],
    m: ['William', 'Oscar', 'Hugo', 'Lucas', 'Elias', 'Axel', 'Erik', 'Filip'],
    f: ['Alice', 'Maja', 'Elsa', 'Astrid', 'Wilma', 'Freja', 'Alva', 'Ebba'],
    l: ['Andersson', 'Johansson', 'Karlsson', 'Nilsson', 'Eriksson', 'Larsson', 'Olsson', 'Lindberg'],
  },
  PL: {
    flag: '🇵🇱', name: '波兰', en: 'Poland', lang: 'pl', fmt: 'SN',
    cities: [['Warszawa', 52.23, 21.01, .05], ['Kraków', 50.06, 19.94, .04], ['Wrocław', 51.11, 17.03, .03], ['Gdańsk', 54.35, 18.65, .03]],
    phones: ['+48 50# ### ###', '+48 60# ### ###', '+48 72# ### ###', '+48 88# ### ###'],
    m: ['Jakub', 'Kacper', 'Szymon', 'Filip', 'Mateusz', 'Antoni', 'Jan', 'Wojciech'],
    f: ['Zuzanna', 'Julia', 'Maja', 'Zofia', 'Hanna', 'Aleksandra', 'Natalia', 'Wiktoria'],
    l: ['Nowak', 'Kowalski', 'Wiśniewski', 'Wójcik', 'Kowalczyk', 'Kamiński', 'Lewandowski', 'Zieliński'],
  },
  CZ: {
    flag: '🇨🇿', name: '捷克', en: 'Czechia', lang: 'cs', fmt: 'SN',
    cities: [['Praha', 50.08, 14.43, .04], ['Brno', 49.20, 16.61, .03], ['Ostrava', 49.84, 18.29, .03]],
    phones: ['+420 601 ### ###', '+420 605 ### ###', '+420 720 ### ###', '+420 777 ### ###'],
    m: ['Jakub', 'Jan', 'Tomáš', 'Adam', 'Matyáš', 'Filip', 'Vojtěch', 'Ondřej'],
    f: ['Eliška', 'Anna', 'Adéla', 'Tereza', 'Sofie', 'Karolína', 'Veronika', 'Lucie'],
    l: ['Novák', 'Svoboda', 'Novotný', 'Dvořák', 'Černý', 'Procházka', 'Kučera', 'Veselý'],
  },
  PT: {
    flag: '🇵🇹', name: '葡萄牙', en: 'Portugal', lang: 'pt', fmt: 'S,N',
    cities: [['Lisboa', 38.72, -9.14, .04], ['Porto', 41.15, -8.61, .03], ['Coimbra', 40.21, -8.42, .02]],
    phones: ['+351 91# ### ###', '+351 93# ### ###', '+351 96# ### ###'],
    m: ['João', 'Francisco', 'Santiago', 'Afonso', 'Duarte', 'Miguel', 'Tomás', 'Rodrigo'],
    f: ['Maria', 'Leonor', 'Matilde', 'Beatriz', 'Carolina', 'Mariana', 'Ana', 'Inês'],
    l: ['Silva', 'Santos', 'Ferreira', 'Pereira', 'Oliveira', 'Costa', 'Rodrigues', 'Martins'],
  },
  JP: {
    flag: '🇯🇵', name: '日本', en: 'Japan', lang: 'ja', fmt: 'SN',
    cities: [['東京', 35.68, 139.75, .07], ['大阪', 34.69, 135.50, .05], ['京都', 35.01, 135.76, .03], ['名古屋', 35.17, 136.90, .04]],
    phones: ['+81 90 #### ####', '+81 80 #### ####', '+81 70 #### ####'],
    m: ['蓮', '大翔', '悠真', '陽翔', '湊', '樹', '健太', '翔太'],
    f: ['陽葵', '凛', '結菜', '芽依', '葵', '紬', '美咲', '楓'],
    l: ['佐藤', '鈴木', '高橋', '田中', '伊藤', '渡辺', '山本', '中村'],
    mr: ['ren', 'hiroto', 'yuma', 'haruto', 'minato', 'itsuki', 'kenta', 'shota'],
    fr: ['himari', 'rin', 'yuna', 'mei', 'aoi', 'tsumugi', 'misaki', 'kaede'],
    lr: ['sato', 'suzuki', 'takahashi', 'tanaka', 'ito', 'watanabe', 'yamamoto', 'nakamura'],
  },
  KR: {
    flag: '🇰🇷', name: '韩国', en: 'South Korea', lang: 'ko', fmt: 'SN',
    cities: [['서울', 37.55, 126.99, .07], ['부산', 35.16, 129.06, .05], ['인천', 37.46, 126.70, .04]],
    phones: ['+82 10 #### ####'],
    m: ['민준', '서준', '도윤', '예준', '시우', '하준', '지호', '준우'],
    f: ['서연', '서윤', '지우', '하은', '민서', '지유', '윤서', '채원'],
    l: ['김', '이', '박', '최', '정', '강', '조', '윤'],
    mr: ['minjun', 'seojun', 'doyun', 'yejun', 'siwoo', 'hajun', 'jiho', 'junwoo'],
    fr: ['seoyeon', 'seoyun', 'jiwoo', 'haeun', 'minseo', 'jiyu', 'yunseo', 'chaewon'],
    lr: ['kim', 'lee', 'park', 'choi', 'jung', 'kang', 'cho', 'yun'],
  },
  TW: {
    flag: '🇹🇼', name: '中国台湾', en: 'Taiwan', lang: 'zh-TW', fmt: 'SN',
    cities: [['台北', 25.04, 121.55, .05], ['台中', 24.15, 120.66, .04], ['高雄', 22.63, 120.30, .04]],
    phones: ['+886 9## ### ###'],
    m: ['家豪', '志明', '俊傑', '建宏', '冠宇', '宗翰', '柏翰', '承翰'],
    f: ['淑芬', '雅婷', '怡君', '心怡', '佳穎', '詩涵', '宜蓁', '子涵'],
    l: ['陳', '林', '黃', '張', '李', '王', '吳', '劉'],
    mr: ['jiahao', 'zhiming', 'junjie', 'jianhong', 'guanyu', 'zonghan', 'bohan', 'chenghan'],
    fr: ['shufen', 'yating', 'yijun', 'xinyi', 'jiaying', 'shihan', 'yizhen', 'zihan'],
    lr: ['chen', 'lin', 'huang', 'zhang', 'li', 'wang', 'wu', 'liu'],
  },
  SG: {
    flag: '🇸🇬', name: '新加坡', en: 'Singapore', lang: 'en', fmt: 'NS',
    cities: [['Singapore', 1.32, 103.85, .07]],
    phones: ['+65 8### ####', '+65 9### ####'],
    m: ['Wei Ming', 'Jun Jie', 'Kai Wen', 'Zhi Hao', 'Arjun', 'Ryan', 'Ethan', 'Daniel'],
    f: ['Hui Ling', 'Xin Yi', 'Jia Hui', 'Mei Ling', 'Priya', 'Chloe', 'Rachel', 'Sarah'],
    l: ['Tan', 'Lim', 'Lee', 'Ng', 'Wong', 'Goh', 'Chua', 'Ong'],
  },
  AU: {
    flag: '🇦🇺', name: '澳大利亚', en: 'Australia', lang: 'en', fmt: 'NS',
    cities: [['Sydney', -33.87, 151.21, .06], ['Melbourne', -37.81, 144.96, .06], ['Brisbane', -27.47, 153.02, .05], ['Perth', -31.95, 115.86, .05]],
    phones: ['+61 4## ### ###'],
    m: ['Jack', 'Oliver', 'William', 'Noah', 'Thomas', 'Lachlan', 'Cooper', 'Henry'],
    f: ['Charlotte', 'Olivia', 'Mia', 'Amelia', 'Isla', 'Grace', 'Ruby', 'Matilda'],
    l: ['Smith', 'Jones', 'Williams', 'Brown', 'Wilson', 'Taylor', 'Kelly', 'Ryan'],
  },
  BR: {
    flag: '🇧🇷', name: '巴西', en: 'Brazil', lang: 'pt-BR', fmt: 'S,N',
    cities: [['São Paulo', -23.55, -46.64, .07], ['Rio de Janeiro', -22.91, -43.20, .05], ['Curitiba', -25.43, -49.27, .04]],
    phones: ['+55 11 9#### ####', '+55 21 9#### ####', '+55 41 9#### ####'],
    m: ['Miguel', 'Arthur', 'Gael', 'Heitor', 'Davi', 'Gabriel', 'Bernardo', 'Lucas'],
    f: ['Helena', 'Alice', 'Laura', 'Maria', 'Valentina', 'Heloísa', 'Júlia', 'Lívia'],
    l: ['Silva', 'Santos', 'Oliveira', 'Souza', 'Lima', 'Pereira', 'Costa', 'Almeida'],
  },
  VN: {
    flag: '🇻🇳', name: '越南', en: 'Vietnam', lang: 'vi', fmt: 'SN',
    cities: [['Thành phố Hồ Chí Minh', 10.77, 106.72, 0.07], ['Hà Nội', 21.03, 105.85, 0.07], ['Đồng Nai', 10.92, 106.85, 0.05], ['Hải Phòng', 20.88, 106.68, 0.05]],
    phones: ['+84 90 ### ####', '+84 91 ### ####', '+84 96 ### ####', '+84 98 ### ####'],
    m: ['Minh', 'Hùng', 'Duy', 'Quang', 'Anh Tuấn', 'Đức', 'Hoàng', 'Nam'],
    f: ['Linh', 'Hương', 'Thảo', 'Ngọc', 'Trang', 'Hà', 'Mai', 'Phương'],
    l: ['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Vũ', 'Đặng', 'Bùi'],
  },
  HK: {
    name: '中国香港', en: 'Hong Kong', lang: 'en', fmt: 'NS',
    cities: [['Hong Kong', 22.28, 114.16, 0.05], ['Kowloon', 22.32, 114.18, 0.04], ['Sha Tin', 22.38, 114.19, 0.03], ['Tuen Mun', 22.39, 113.97, 0.03]],
    phones: ['+852 5### ####', '+852 6### ####', '+852 9### ####'],
    m: ['志明', '家輝', '偉業', '俊傑', '國榮', '嘉豪', '子軒', '浩然'],
    f: ['嘉欣', '詠琪', '美玲', '淑儀', '子瑜', '曉彤', '雅雯', '思穎'],
    l: ['陳', '黃', '李', '張', '劉', '梁', '吳', '周'],
    mr: ['chiming', 'kafai', 'waiyip', 'chunkit', 'kwokwing', 'kahou', 'tszhin', 'houyin'],
    fr: ['kayan', 'wingkei', 'meiling', 'sukyee', 'tszyu', 'hiutung', 'ngaman', 'szewing'],
    lr: ['chan', 'wong', 'lee', 'cheung', 'lau', 'leung', 'ng', 'chau'],
  },
  TH: {
    name: '泰国', en: 'Thailand', lang: 'th', fmt: 'NS',
    cities: [['Bangkok', 13.75, 100.49, 0.07], ['Nonthaburi', 13.84, 100.49, 0.03], ['Phra Pradaeng', 13.66, 100.53, 0.03], ['Pak Kret', 13.91, 100.50, 0.03]],
    phones: ['+66 8# ### ####', '+66 9# ### ####', '+66 6# ### ####'],
    m: ['สมชาย', 'สมศักดิ์', 'วิชัย', 'ประเสริฐ', 'อานนท์', 'ณัฐพล', 'ธนกร', 'กิตติศักดิ์'],
    f: ['มาลี', 'สุดา', 'นภา', 'พรทิพย์', 'วิภา', 'ศิริพร', 'กัญญา', 'อรุณี'],
    l: ['ใจดี', 'สุขสวัสดิ์', 'วงศ์สวัสดิ์', 'ศรีสุข', 'บุญมี', 'ทองดี', 'รัตนกุล', 'พงศ์พันธ์'],
    mr: ['somchai', 'somsak', 'wichai', 'prasert', 'anon', 'nattapon', 'thanakorn', 'kittisak'],
    fr: ['malee', 'suda', 'napa', 'porntip', 'wipa', 'siriporn', 'kanya', 'arunee'],
    lr: ['jaidee', 'suksawat', 'wongsawat', 'srisuk', 'boonmee', 'thongdee', 'rattanakul', 'pongpan'],
  },
  PH: { // 由 add-country.js 自动生成（电话/姓名池由 AI 补全）
    name: '菲律宾', en: 'Philippines', lang: 'en', fmt: 'NS',
    cities: [['Quezon City', 14.65, 121.05, 0.05], ['Manila', 14.59, 120.98, 0.04], ['Antipolo', 14.59, 121.18, 0.04], ['Taguig', 14.53, 121.07, 0.04]],
    phones: ['+63 917 ### ####', '+63 918 ### ####', '+63 919 ### ####', '+63 920 ### ####', '+63 915 ### ####'],
    m: ['Jose', 'Juan', 'Miguel', 'Angelo', 'Rafael', 'Christian', 'Joshua', 'Marco'],
    f: ['Maria', 'Angelica', 'Nicole', 'Andrea', 'Camille', 'Bianca', 'Kathryn', 'Jasmine'],
    l: ['Santos', 'Reyes', 'Cruz', 'Garcia', 'Mendoza', 'Bautista', 'Villanueva', 'Aquino'],
  },
  MY: { // 由 add-country.js 自动生成；部分字段为通用占位，建议按当地习惯完善
    name: '马来西亚', en: 'Malaysia', lang: 'en', fmt: 'NS',
    cities: [['Kuala Lumpur', 3.15, 101.69, 0.04], ['Kajang', 2.99, 101.79, 0.04], ['Subang Jaya', 3.05, 101.58, 0.04], ['Klang', 3.04, 101.44, 0.04]],
    phones: ['+60 123 ### ###'],
    m: ['Muhamad', 'Ahmad', 'Adam', 'Amar', 'Wan', 'Iman', 'Harraz', 'Izz'],
    f: ['Nur', 'Wan', 'Nurul', 'Aisyah', 'Maryam', 'Siti', 'Dhia', 'Naura'],
    l: ['Nguyen', 'Santos', 'Novak', 'Kova', 'Petrov', 'Haddad', 'Okoro', 'Yilmaz'],
  },
  TR: { // 由 add-country.js 自动生成（电话/姓名池来自开源数据集）
    name: '土耳其', en: 'Türkiye', lang: 'tr', fmt: 'SN',
    cities: [['Ankara', 39.92, 32.85, 0.07], ['Adana', 36.99, 35.33, 0.05], ['Gaziantep', 37.06, 37.38, 0.05], ['Konya', 37.87, 32.49, 0.05]],
    phones: ['+90 501 ### ####'],
    m: ['Mehmet', 'Mustafa', 'Ahmet', 'Ali', 'Hüseyin', 'Hasan', 'Ibrahim', 'İsmail'],
    f: ['Fatma', 'Ayşe', 'Emine', 'Hatice', 'Zeynep', 'Elif', 'Meryem', 'Şerife'],
    l: ['Yılmaz', 'Kaya', 'Demir', 'Şahin', 'Çelik', 'Yıldız', 'Yıldırım', 'Öztürk'],
  },
};

const EMAIL_DOMAINS = ['gmail.com', 'outlook.com', 'yahoo.com', 'hotmail.com', 'proton.me'];
